### ISSUE TITLE
Support for Pyodide 0.23.1

### ISSUE THREAD

**Issue by elilambnz** [pyodide/pyodide-webpack-plugin#14]
It appears that files to copy are only specified for versions `0.21.3` and `0.22.1`.

With version `0.23.1`, the following error occurs:

```
unable to locate './node_modules/pyodide/pyodide_py.tar' glob
unable to locate './node_modules/pyodide/pyodide.asm.data' glob
```

**Comment by hoodmane** [comment]
Need to remove those two and add `python_stdlib.zip`.

**Comment by mneil** [comment]
Works in 1.1.0
