### ISSUE TITLE
PyodidePlugin is not a constructor

### ISSUE THREAD

**Issue by haoxl3** [pyodide/pyodide-webpack-plugin#17]
<img width="584" alt="image" src="https://github.com/pyodide/pyodide-webpack-plugin/assets/15046133/378a7dbf-9b1a-4226-a9b7-40ae41bb719a">
then I got error `PyodidePlugin is not a constructor`

pyodide version: 0.23.4
node version: 16.18.0

**Comment by mneil** [comment]
At a glance you have the line `new PypodidePlugin()` in the example block but you have not imported that from anywhere. If you were to show line numbers and a complete stack trace of the error I suspect it would point to that specific line and that the fix would be that you need to import that class from the module and have not done so.

**Comment by haoxl3** [comment]
> 乍一看，`new PypodidePlugin()`示例块中有该行，但您尚未从任何地方导入它。如果您要显示行号和错误的完整堆栈跟踪，我怀疑它会指向该特定行，并且修复方法是您需要从模块导入该类，但尚未这样做。

**Comment by haoxl3** [comment]
> At a glance you have the line `new PypodidePlugin()` in the example block but you have not imported that from anywhere. If you were to show line numbers and a complete stack trace of the error I suspect it would point to that specific line and that the fix would be that you need to import that class from the module and have not done so.

I've already imported it, but I don't show you the imported code

**Comment by tcztzy** [comment]
I got the same problem. Solved by change the import statement
```javascript
// the import statement in README doesn't work
// const PyodidePlugin = require("@pyodide/webpack-plugin");
// change as the following works
const { PyodidePlugin } = require("@pyodide/webpack-plugin");
```
