### ISSUE TITLE
Pyodide 0.24.0 rename repodata.json to pyodide-lock.json

### ISSUE THREAD

**Issue by tcztzy** [pyodide/pyodide-webpack-plugin#18]
I got the exception about the `repodata.json` is missing.
https://github.com/pyodide/pyodide/pull/3824

**Comment by mneil** [comment]
Can you provide some information about what version of pyodide and which version of the webpack plugin you are using?

**Comment by dlech** [comment]
Pyodide v0.24 was released just a few days ago. Basically, we need a change similar to https://github.com/pyodide/pyodide-webpack-plugin/commit/3e15ef05ec155d9fde4af0bc42cac2fde266c435 for the `repodata.json` -> `pyodide-lock.json` rename.

**Comment by mneil** [comment]
version [1.2.0](https://www.npmjs.com/package/@pyodide/webpack-plugin/v/1.2.0) is available and addresses this issue. Thanks!
