### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by dlech** [pyodide/pyodide-webpack-plugin#21]
I'm getting "Critical dependency: the request of a dependency is an expression" when building my app which I assume is triggered by the dynamic imports in some of the pyodide files. The README here suggests to use `string-replace-loader` but I couldn't get that to work. But I found https://stackoverflow.com/a/59235546/1976323 which suggests the following to work around the issue for now.

```js
new webpack.ContextReplacementPlugin(/pyodide/)
```

It would be nice, though, if a fix was just built into this plugin someshow so that we we can just use this plugin and everything works without additional hacks.

**Comment by mneil** [comment]
Resolved in #22
