### ISSUE TITLE
Attempted import error: 'version' is not exported from 'pyodide' (imported as 'pyodideVersion').

### ISSUE THREAD

**Issue by dlech** [pyodide/pyodide-webpack-plugin#25]
This might be an upstream issue, but since pyodide-webpack-plugin v1.3, we are getting

```console
Attempted import error: 'version' is not exported from 'pyodide' (imported as 'pyodideVersion').
```

on this line of code

```ts
import { loadPyodide, version as pyodideVersion } from 'pyodide';
```

I think this has to do with the fact that `pyodide.js` has

```js
try{Object.assign(exports,loadPyodide)}catch(_){}
```

while `pyodide.mjs` has

```js
export{De as loadPyodide,k as version};
```

I'm guessing that pyodide-webpack-plugin must have changed which of those two files it being used?

(pyodide v0.24.1)

**Comment by mneil** [comment]
If your project importing pyodide is declared as a module then the plugin will load pyodide.mjs. If you are not using modules then it will load pyodide.js. Or, if your webpack output targets esm then it chooses pyodide.mjs. Can you share the webpack config that is causing the issue?

**Comment by dlech** [comment]
The project is an ejected Create React App and uses typescript.

- https://github.com/pybricks/pybricks-code/blob/master/config/webpack.config.js
- https://github.com/pybricks/pybricks-code/blob/master/tsconfig.json

**Comment by mneil** [comment]
@pyodide/webpack-plugin@1.3.2 fixes this error.

**Comment by dlech** [comment]
Seems to be working, thanks!
