### ISSUE TITLE
Can't get packages to load from packageIndexUrl's default

### ISSUE THREAD

**Issue by zloveless** [pyodide/pyodide-webpack-plugin#28]
I saw [this reply](https://github.com/pyodide/pyodide-webpack-plugin/issues/4#issuecomment-1257001194) in #4 and now I'm wondering if I'm using this wrong because I can't seem to get micropip loaded using this plugin.

I am trying to make use of pyodide in a react app like so; it's basically what you guys have on the readme in this repo, plus micropip. I'm not trying to make use of micropip right now, just trying to solve that it's not loading.

Relevant package.json versions. I can post the full dependencies if needed, but I figured I'd extract the probably relevant ones:
* "pyodide": "^0.26.1",
* "@pyodide/webpack-plugin": "^1.3.2",
* "copy-webpack-plugin": "^12.0.2",
* "webpack": "^5.91.0",
* "webpack-dev-server": "^5.0.4"

```typescript
  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const pyodide = await loadPyodide({
      indexURL: `${window.location.origin}/pyodide`,
    });
    await pyodide.loadPackage('micropip', { checkIntegrity: false }); // checkIntegrity: false was a test
    pyodide.pyimport('micropip');
    const result = await pyodide.runPythonAsync(`
      print("Hello from edit page")
`);
    console.log(result);
  };
```
Commenting out the loadPackage() and pyimport() calls I'm able to see the result of my `console.log(result)`, so pyodide itself is being loaded. But the console indicates it's trying to fetch the micropip and packaging wheels from the indexURL which is localhost. 

![image](https://github.com/pyodide/pyodide-webpack-plugin/assets/385946/76bbee73-eeec-4b7f-90fd-0a776cebdf9e)

My webpack plugin configuration:
```typescript
    plugins: [
        new PyodidePlugin(), // **
        new MiniCssExtractPlugin(),
        new HtmlWebpackPlugin({
            template: './public/index.html',
            inject: 'head',
        }),
        new CopyPlugin({
            patterns: [
                { from: './src/data.json', to: './[name].json' },
                { from: `../dist/*.whl`, to: './pyodide/[name].whl' }
            ]
        }),
    ],
```
I indeed tried setting the `packageIndexUrl` to what the documentation says is its default (both as a string and leaving it off entirely as seen above. 

The import for webpack.config.ts
```typescript
import { PyodidePlugin } from '@pyodide/webpack-plugin';
```

The pyodide error, if it matters:
```
PythonError: Traceback (most recent call last):
  File "/lib/python312.zip/_pyodide/_base.py", line 629, in pyimport_impl
    res = __import__(stem, fromlist=fromlist)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'micropip'
The module 'micropip' is included in the Pyodide distribution, but it is not installed.
You can install it by calling:
  await micropip.install("micropip") in Python, or
  await pyodide.loadPackage("micropip") in JavaScript
See https://pyodide.org/en/stable/usage/loading-packages.html for more details.
```

**Comment by mneil** [comment]
Hi @zloveless, thanks for raising this issue. The documentation could be clearer about this.

The first screenshot you have shows that these files are missing from your local dev server. The examples show basic usage of pyodide and the plugin without any other packages installed. I realize once you start actually adding packages and micropip it gets more complicated.

By default, pyodide (not the plugin) [tries to load packages like micropip and other pip packages local](https://pyodide.org/en/stable/usage/api/js-api.html) to the pyodide.js location. What that means is you would need to download or build micropip and place it at some path available on your dev server, typically `/micropip-0.6.0-py3-none-any.whl` or similar by default. The examples show changing that indexURL to keep packages out of the root `/` folder and placing them in `/pyodide` for organization. 

> I will note for security this is preferred and is intended behavior. See [supply chain security](https://snyk.io/blog/polyfill-supply-chain-attack-js-cdn-assets/) 

What you might be interested in for simple testing and verification of the tool is to use the CDN hosted packages that pyodide provides. You can do that by setting the `indexURL` in your handleSubmit function to `https://cdn.jsdelivr.net/pyodide/v0.26.1/full/`. This should get you running again and will provide the same behavior as if you were [serving pyodide from the CDN](https://pyodide.org/en/stable/usage/downloading-and-deploying.html).

Please let me know if that resolves your issue.

**Comment by zloveless** [comment]
Hi @mneil, this seems to work, thanks! My handleSubmit() now looks like this:

```typescript
  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const pyodide = await loadPyodide({
      indexURL: 'https://cdn.jsdelivr.net/pyodide/v0.26.1/full/'
    });
    await pyodide.loadPackage('micropip');
    pyodide.pyimport('micropip');
    const wheel = 'my-redacted-wheel.whl'; // TODO!
    pyodide.loadPackage(wheel);
    pyodide.runPython(codeModel);
  };
```
