### ISSUE TITLE
acorn-import-assertions is no longer available if using newer webpack

### ISSUE THREAD

**Issue by yuttie** [pyodide/pyodide-webpack-plugin#29]
The `acorn-import-assertions` package is used [here](https://github.com/pyodide/pyodide-webpack-plugin/blob/cb119a3198a364782de9a8dc4f558fcd03c71e1f/loader.ts#L2), but it is missing from `package.json` as a direct dependency.

With older versions of webpack (e.g. v5.88.2 as indicated in the [`package-lock.json`](https://github.com/pyodide/pyodide-webpack-plugin/blob/cb119a3198a364782de9a8dc4f558fcd03c71e1f/package-lock.json#L6719-L6730)), `acorn-import-assertions` is installed indirectly as a dependency of webpack, so the issue does not surface.

However, with recent versions of webpack, `acorn-import-assertions` is no longer the dependency of webpack, which leads to a build error:
```
ERROR in ./node_modules/pyodide/pyodide.mjs
Module build failed (from ./node_modules/@pyodide/webpack-plugin/loader.cjs):
Error: Cannot find module 'acorn-import-assertions'
```

**Comment by mneil** [comment]
Fixed in #30 . @pyodide/webpack-plugin version `1.3.3` should resolve the issue.
