### ISSUE TITLE
Webpack url not found

### ISSUE THREAD

**Issue by mneil** [pyodide/pyodide-webpack-plugin#8]
from @msebas regarding #6 

After building your fix `5d3ec27` I installed it to the test project. Trying to run the dev server using `npm run serve` I got an unrelated error stating that `Module not found: Error: Can't resolve 'url' in ...`, so I installed url using `npm install --save-dev url` and checked if `node_modules/@pyodide/webpack-plugin` was not updated by npm. Now the dev server starts up.
To do something with pyodide I updated `src/main.js` to be
```
import { createApp } from 'vue'
import App from './App.vue'
import {loadPyodide} from "pyodide";

createApp(App).mount('#app')
let pyodide = null;
async function main() {
  pyodide = await loadPyodide({ indexURL: `${window.location.origin}/pyodide` });
  return pyodide.runPython(`
    import sys
    sys.version
  `)
}
main().then(r => console.log(r));
```
(following the example in the `README.md`)

The dev-Server starts now, but loading `http://localhost:8080/` leads to a console error
```
Uncaught (in promise) Error: Cannot find module 'http://localhost:8080/pyodide/pyodide.asm.js'
    webpackEmptyAsyncContext app.js:99
    promise callback*webpackEmptyAsyncContext app.js:98
    loadScript compat.ts:158
    loadPyodide pyodide.ts:308
    main main.js:8
    <anonymous> main.js:15
    js app.js:63
    __webpack_require__ app.js:277
    __webpack_exports__ app.js:1499
    O app.js:326
    <anonymous> app.js:1500
    <anonymous> app.js:1502
app.js:99:11
```
which is cause by the function 
```
function webpackEmptyAsyncContext(req) {
	// Here Promise.resolve().then() is used instead of new Promise() to prevent
	// uncaught exception popping up in devtools
	return Promise.resolve().then(function() {
		var e = new Error("Cannot find module '" + req + "'");
		e.code = 'MODULE_NOT_FOUND';
		throw e;
	});
}
```
that seems to be loaded by pyodide using
`loadScript = async url => await __webpack_require__("./node_modules/pyodide lazy recursive")(url)`
where `url` is the string `"http://localhost:8080/pyodide/pyodide.asm.js"` (strangely calling the URL itself returns said script from the pyodide main module). 

Guessing that the value of `url` might be not valid for webpacks resolving mechanism I dropped the `indexURL` from `main.js` (loading pyodide via `pyodide = await loadPyodide();`). This resulted in the same error, only the value of `url` changed to `"webpack-internal:///./node_modules/pyodide/pyodide.asm.js"`.

I am a little bit at a loss what makes webpack screw up here, because the first value of `url` serves what is required.

**Comment by mneil** [comment]
FWIW I also tried this yesterday and ran into the same issue and tried the same fixes. I'm not sure if this is webpack / config related or pyodide module (.mjs) issue. I haven't tried this plugin beyond your initial issue with vue nor have I used the esm version of pyodide yet. I'll try to debug this and let you know how it goes. Thank you again for another thorough bug report.

**Comment by mneil** [comment]
Added documentation addressing this issue https://github.com/pyodide/pyodide-webpack-plugin#known-issues-with-esm.

Specifically, for vue cli, you need to install the string-replace-loader from the docs and then edit `vue.config.mjs` to add the `chainWebpack` option.

```
export default defineConfig({
  configureWebpack: () => {
    return {
      plugins: [new PyodidePlugin()],
      resolve: {
        fallback: {
          url: require.resolve("url/"),
        },
      },
    };
  },
  transpileDependencies: true,
  // Force webpack to leave import statements alone
  chainWebpack: (config) => {
    config.module
      .rule("pyodide")
      .test(/pyodide\.m?js$/)
      .use()
      .loader("string-replace-loader")
      .options({
        search: "import(",
        replace: "import(/* webpackIgnore: true */ ",
      });
  },
});
```

**Comment by hoodmane** [comment]
I am so glad that you are maintaining this @mneil since there is probably no way any of the rest of us would have been able to figure this out...
